# -*- coding: utf-8 -*-
"""phone_payipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-qxgjSLj3gQWAd9GpVQrLymTRLxquio
"""

!git clone https://github.com/PhonePe/pulse.git

import os
path="/content/pulse/data/aggregated/user/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="/content/pulse/data/aggregated/user/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_type':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['aggregated']:
              Name=z['name']
              count=z['paymentInstruments'][0]['count']
              amount=z['paymentInstruments'][0]['amount']
              clm['Transacion_type'].append(Name)
              clm['Transacion_count'].append(count)
              clm['Transacion_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Agg_Insurance=pd.DataFrame(clm)



Agg_Insurance

Agg_Insurance.to_csv('Agg_Insurance.csv', index=False)

from google.colab import files

files.download('Agg_Insurance.csv')

import os
path="/content/pulse/data/aggregated/user/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

import pandas as pd
import json
import os

path = "/content/pulse/data/aggregated/user/country/india/state/"
Agg_state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quater': [],
    'registered_Users': [],
    'app_opens':[],
    'User_brand': [],
    'User_count': [],
    'User_percentage': []
}

for i in Agg_state_list:
    p_i = os.path.join(path, i)
    Agg_yr = os.listdir(p_i)
    for j in Agg_yr:
        p_j = os.path.join(p_i, j)
        Agg_yr_list = os.listdir(p_j)
        for k in Agg_yr_list:
            p_k = os.path.join(p_j, k)
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # Extract values from the JSON structure
                registered_users = D['data']['aggregated'].get('registeredUsers', 0)
                app_opens = D['data']['aggregated'].get('appOpens', 0)
                users_by_device = D['data'].get('usersByDevice', [])
            if users_by_device is not None:
                for device in users_by_device:
                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                    clm['registered_Users'].append(registered_users)
                    clm['app_opens'].append(app_opens)
                    clm['User_brand'].append(device.get('brand', 'Unknown'))
                    clm['User_count'].append(device.get('count', 0))
                    clm['User_percentage'].append(device.get('percentage', 0.0))

# Create the DataFrame
Agg_User = pd.DataFrame(clm)

Agg_User

Agg_User.to_csv('Agg_User.csv', index=False)

from google.colab import files

files.download('Agg_User.csv')

import os
path="/content/pulse/data/map/transaction/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="/content/pulse/data/map/transaction/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Transacion_dist':[], 'Transacion_count':[], 'Transacion_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              clm['Transacion_dist'].append(Name)
              clm['Transacion_count'].append(count)
              clm['Transacion_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Map_Trans=pd.DataFrame(clm)

Map_Trans

Map_Trans.to_csv('Map_Trans.csv', index=False)

from google.colab import files

files.download('Map_Trans.csv')

import os
path="/content/pulse/data/map/insurance/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

#Once created the clone of GIT-HUB repository then,
#Required libraries for the program

import pandas as pd
import json
import os

#This is to direct the path to get the data as states

path="/content/pulse/data/map/insurance/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list
#Agg_state_list--> to get the list of states in India

#<------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>#

#This is to extract the data's to create a dataframe

clm={'State':[], 'Year':[],'Quater':[],'Insurance_dist':[], 'Insurance_count':[], 'Insurance_amount':[]}

for i in Agg_state_list:
    p_i=path+i+"/"
    Agg_yr=os.listdir(p_i)
    for j in Agg_yr:
        p_j=p_i+j+"/"
        Agg_yr_list=os.listdir(p_j)
        for k in Agg_yr_list:
            p_k=p_j+k
            Data=open(p_k,'r')
            D=json.load(Data)
            for z in D['data']['hoverDataList']:
              Name=z['name']
              count=z['metric'][0]['count']
              amount=z['metric'][0]['amount']
              clm['Insurance_dist'].append(Name)
              clm['Insurance_count'].append(count)
              clm['Insurance_amount'].append(amount)
              clm['State'].append(i)
              clm['Year'].append(j)
              clm['Quater'].append(int(k.strip('.json')))
#Succesfully created a dataframe
Map_Insurance=pd.DataFrame(clm)

Map_Insurance

Map_Insurance.to_csv('Map_Insurance.csv', index=False)

from google.colab import files

files.download('Map_Insurance.csv')

import os
path="/content/pulse/data/map/user/hover/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

import pandas as pd
import json
import os

path = "/content/pulse/data/map/user/hover/country/india/state/"
Agg_state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quater': [],
    'District': [],
    'registered_Users': [],
    'appOpens': []
}

for i in Agg_state_list:
    p_i = os.path.join(path, i)
    Agg_yr = os.listdir(p_i)
    for j in Agg_yr:
        p_j = os.path.join(p_i, j)
        Agg_yr_list = os.listdir(p_j)
        for k in Agg_yr_list:
            p_k = os.path.join(p_j, k)
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                hover_data = D['data'].get('hoverData', {})

                # Now iterate over districts (keys inside hoverData)
                for district, values in hover_data.items():
                    registered_users = values.get('registeredUsers', 0)
                    app_opens = values.get('appOpens', 0)

                    clm['State'].append(i)
                    clm['Year'].append(j)
                    clm['Quater'].append(int(k.strip('.json')))
                    clm['District'].append(district)
                    clm['registered_Users'].append(registered_users)
                    clm['appOpens'].append(app_opens)

# Create the DataFrame
map_user = pd.DataFrame(clm)

map_user

map_user.to_csv('map_user.csv', index=False)

from google.colab import files

files.download('map_user.csv')

import os
path="/content/pulse/data/top/transaction/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

import pandas as pd
import json
import os

path = "/content/pulse/data/top/transaction/country/india/state/"
Agg_state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quater': [],
    'Transacion_State': [],
    'Transacion_District': [],
    'Transacion_Pincode': [],
    'District_trans_count': [],
    'District_trans_amount': [],
    'State_trans_count': [],
    'State_trans_amount': [],
    'pincode_trans_count': [],
    'pincode_trans_amount': []
}

for i in Agg_state_list:
    p_i = os.path.join(path, i)
    Agg_yr = os.listdir(p_i)
    for j in Agg_yr:
        p_j = os.path.join(p_i, j)
        Agg_yr_list = os.listdir(p_j)
        for k in Agg_yr_list:
            p_k = os.path.join(p_j, k)
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # Extract one district (first one, or None if not found)
                district_data = D['data'].get('districts', [])
                if district_data:
                    district_entry = district_data[0]
                    District = district_entry.get('entityName', 'Unknown')
                    district_metric = district_entry.get('metric', {})
                    District_count = district_metric.get('count', 0)
                    District_amount = district_metric.get('amount', 0)
                else:
                    District = 'Unknown'
                    District_count = 0
                    District_amount = 0

                # Extract one state
                state_data = D['data'].get('states', [])
                if state_data:
                    state_entry = state_data[0]
                    StateName = state_entry.get('entityName', 'Unknown')
                    state_metric = state_entry.get('metric', {})
                    State_count = state_metric.get('count', 0)
                    State_amount = state_metric.get('amount', 0)
                else:
                    StateName = 'Unknown'
                    State_count = 0
                    State_amount = 0

                # Now loop through pincodes
                pincodes_data = D['data'].get('pincodes', [])
                if pincodes_data:
                    for a in pincodes_data:
                        Pincode = a.get('entityName', 'Unknown')
                        metric = a.get('metric', {})
                        Pincode_count = metric.get('count', 0)
                        Pincode_amount = metric.get('amount', 0)

                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
                        clm['Transacion_District'].append(District)
                        clm['Transacion_State'].append(StateName)
                        clm['Transacion_Pincode'].append(Pincode)
                        clm['District_trans_count'].append(District_count)
                        clm['District_trans_amount'].append(District_amount)
                        clm['State_trans_count'].append(State_count)
                        clm['State_trans_amount'].append(State_amount)
                        clm['pincode_trans_count'].append(Pincode_count)
                        clm['pincode_trans_amount'].append(Pincode_amount)

# Create the DataFrame
Top_Trans = pd.DataFrame(clm)

Top_Trans

Top_Trans.to_csv('Top_Trans.csv', index=False)

from google.colab import files

files.download('Top_Trans.csv')

import os
path="/content/pulse/data/top/user/country/india/state/"
Agg_state_list=os.listdir(path)
Agg_state_list

import pandas as pd
import json
import os

path = "/content/pulse/data/top/user/country/india/state/"
Agg_state_list = os.listdir(path)

clm = {
    'State': [],
    'Year': [],
    'Quater': [],
    'user_state': [],
    'user_District': [],
    'user_Pincode': [],
    'District_registeredUsers': [],
    'state_registeredUsers': [],
    'pincode_registeredUsers': []
}

for i in Agg_state_list:
    p_i = os.path.join(path, i)
    Agg_yr = os.listdir(p_i)
    for j in Agg_yr:
        p_j = os.path.join(p_i, j)
        Agg_yr_list = os.listdir(p_j)
        for k in Agg_yr_list:
            p_k = os.path.join(p_j, k)
            with open(p_k, 'r') as Data:
                D = json.load(Data)

                # Extract one district (first one, or None if not found)
                district_data = D['data'].get('districts', [])
                if district_data:
                    district_entry = district_data[0]
                    District = district_entry.get('entityName', 'Unknown')
                    district_metric = district_entry.get('metric', {})
                    District_registeredUsers = district_metric.get('registeredUsers', 0)
                else:
                    District = 'Unknown'
                    District_registeredUsers = 0


                # Extract one state
                state_data = D['data'].get('states', [])
                if state_data:
                    state_entry = state_data[0]
                    StateName = state_entry.get('entityName', 'Unknown')
                    state_metric = state_entry.get('metric', {})
                    state_registeredUsers = state_metric.get('registeredUsers', 0)
                else:
                    StateName = 'Unknown'
                    state_registeredUsers = 0


                # Now loop through pincodes
                pincodes_data = D['data'].get('pincodes', [])
                if pincodes_data:
                    for a in pincodes_data:
                        Pincode = a.get('entityName', 'Unknown')
                        pincode_metric = a.get('metric', {})
                        pincode_registeredUsers = pincode_metric.get('registeredUsers', 0)


                        clm['State'].append(i)
                        clm['Year'].append(j)
                        clm['Quater'].append(int(k.strip('.json')))
                        clm['user_District'].append(District)
                        clm['user_state'].append(StateName)
                        clm['user_Pincode'].append(Pincode)
                        clm['District_registeredUsers'].append(District_count)
                        clm['state_registeredUsers'].append(State_count)
                        clm['pincode_registeredUsers'].append(Pincode_count)


# Create the DataFrame
Top_user = pd.DataFrame(clm)

Top_user

Top_user.to_csv('Top_user.csv', index=False)

from google.colab import files

files.download('Top_user.csv')











